name: CI for Bets Ministry

on:
  push:
    branches:
      - lab8
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: fileinfo  # Ensure fileinfo extension is enabled

      - name: Install dependencies
        run: composer install  # You could add `--ignore-platform-reqs` if needed

      - name: Run tests
        run: ./vendor/bin/phpunit tests
