name: CI for Bets Ministry

on:
  push:
    branches:
      - lab8
  pull_request:
    branches:
      - lab8

jobs:
  build:
    runs-on: windows-latest  # Запуск на виртуальной машине с Windows

    steps:
      # Шаг 1: Получить код
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 6: Запустить тесты с помощью PHPUnit
      - name: Run tests
        run: |
          vendor\bin\phpunit tests  # Запускает тесты
