name: CI for Bets Ministry

on:
  push:
    branches:
      - lab8
  pull_request:
    branches:
      - lab8

jobs:
  build:
    runs-on: windows-latest  # Запуск на виртуальной машине с Windows

    steps:
      # Шаг 1: Получить код
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 3: Установить необходимые дополнительные инструменты
      - name: Install additional tools
        run: |
          choco install php --version=8.2--force
          php -m  # Убедимся, что расширения загружены

      # Шаг 5: Установить зависимости через Composer
      - name: Install dependencies
        run: |
          composer install --ignore-platform-reqs  # Игнорируем проблему с расширениями, если не можем их установить

      # Шаг 4: Запустить composer update, чтобы обновить lock файл
      - name: Update Composer dependencies
        run: |
          composer update --ignore-platform-reqs  # Игнорируем проблему с расширениями, если не можем их установить


      # Шаг 6: Запустить тесты с помощью PHPUnit
      - name: Run tests
        run: |
          vendor\bin\phpunit tests  # Запускает тесты
